name: asl1
channels:
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - python=3.8.8
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - cudatoolkit=11.3
  - scikit-learn
  - tqdm
  - pandas
  - pytables
  - scikit-image
  - mosek
  - torchmetrics
  - gensim
  - lightning
  - conda-forge::omegaconf
  - ipykernel
  - ca-certificates
  - certifi
  - openssl
  - conda-forge::higher
prefix: /mnt/raptor/hassan/anaconda3/envs/asl1
